### ISSUE TITLE
<mrk> tags not present after conversion to .sdlxliff

### ISSUE THREAD

**Issue by stelmath** [sdl/trados-studio-api-samples#15]
Hello there,

I have followed the example codes to create a C# console app that simply takes as input: source language, target language, source Word file and produces .sdlxliff files (one for the source language, and one for each target language). However, I am noticing that in the resulting .sdlxliffs, inside the `<trans-unit>`s , inside the `<seg-source>` tag, there are NO `<mrk>` tags of `mtype` "seg" present. But, if I open one of those .sdlxliff files in Trados and hit Control+S, then if I open that .sdlxliff using Notepad++, for example, then I can see that the `<mrk>` tags have been populated. So, how can I use the SDK API to also create these <mrk> tags WITHOUT opening Trados Studio at all? 

Here is an example of a seg-source from the .sdlxliff that my C# app creates:
![image](https://user-images.githubusercontent.com/38814495/107768004-7566bf80-6d3e-11eb-8025-617d638596be.png)
Notice the absence of any `<mrk>` tags

And here is the same seg-source after I simply open this .sdlxliff in Trados and hit Control+S:
![image](https://user-images.githubusercontent.com/38814495/107768116-a0511380-6d3e-11eb-862e-094fb765ebd4.png)
As you can see, Trados has further segmented my original seg-source into 2 separate segments. These segments, are of course 2 separate rows in the Trados Editor window. 

My code follows the tutorial closely, but I am not using any TM in the `FileBasedProject`. Am I missing some code in my C# app that can execute this segmentation for me, without me having to manually open the .sdlxliffs in Trados Studio? **Please help - this is urgent! Thanks**

**Comment by stelmath** [comment]
Looks like I was able to force it to produce `<mrk>` tags in the .sdlxliffs by using the PreTranslate task. My code looks something like:

```C#
FileBasedProject newProject = new FileBasedProject(this.GetProjectInfo(srcLocale, trgLocale, ouputpath, uniqueid));

this.AddFiles(newProject, wordFilePath);  // just like SDK documentation
this.ConvertFiles(newProject);  // just like SDK documentation
this.ApplyPreTranslateSettings(newProject);
this.Pretranslate(newProject);
```

and also 
```C#
private void ApplyPreTranslateSettings(FileBasedProject project)
{
    // get TM specific settings
    ISettingsBundle settings = project.GetSettings();
    TranslateTaskSettings pretranslateSettings = settings.GetSettingsGroup<TranslateTaskSettings>();
                
    pretranslateSettings.MinimumMatchScore.Value = 99;  // fuzzy-match minimum score
    pretranslateSettings.ConfirmAfterApplyingExactMatch.Value = false;  // confirmed matched appear with an icon on the Trados UI
    pretranslateSettings.LockExactMatchSegments.Value = false;  // lock exact matches from editing
    pretranslateSettings.ConfirmAfterApplyingInContextExactMatch.Value = false;
    pretranslateSettings.LockContextMatchSegments.Value = false;

    pretranslateSettings.NoTranslationMemoryMatchFoundAction.Value = NoTranslationMemoryMatchFoundAction.LeaveEmpty;  // this is the default action            
    pretranslateSettings.TranslationOverwriteMode.Value = TranslationUpdateMode.KeepExistingTranslation;  // dont over write
    
    project.UpdateSettings(settings);
}
public void Pretranslate(FileBasedProject project)
{
    // loop over the target language codes of the project
    foreach (Language iso_lang_code in project.GetProjectInfo().TargetLanguages)
    {
        ProjectFile[] targetFiles = project.GetTargetLanguageFiles(new Language(CultureInfo.GetCultureInfo(iso_lang_code.CultureInfo.Name)));

        AutomaticTask translateTask = project.RunAutomaticTask(
            targetFiles.GetIds(),
            AutomaticTaskTemplateIds.PreTranslateFiles);
    }
}
  
```

Is this the standard way of getting the `<mrk>` tags or should I use another method? Thanks!

**Comment by cromica** [comment]
By default Studio runs PreTranslate task. Yes PreTransalte can generate this tags.
